title: Yang Yu's Homepage
page-top-title: Yang Yu
top-section-bg-text: University of Science and Technology of China (USTC)
home-subtitle: Yang Yu&ensp;|&ensp;於阳
copyright-text: '&copy; Yang Yu 2026-2026. All Rights Reserved.'
